CREATE DATABASE IF NOT EXISTS ECOMMERCE_BLACK;
USE ECOMMERCE_BLACK;

-- 1. Roles (Admin, Cliente)
CREATE TABLE ROL (
    ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_ROL VARCHAR(50) NOT NULL
);

-- 2. Usuarios (Combinando tu idea de USUARIOS_ADMIN y Clientes)
CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_ROL_REF INT,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ROL_REF) REFERENCES ROL(ID_ROL)
);

-- 3. Categorías (Dama, Caballero, Niños)
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CATEGORIA VARCHAR(50) NOT NULL
);

-- 4. Productos
CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PRODUCTO VARCHAR(150) NOT NULL,
    DESCRIPCION TEXT,
    PRECIO DECIMAL(10,2) NOT NULL,
    STOCK INT DEFAULT 0,
    IMAGEN_URL VARCHAR(255),
    ID_CATEGORIA_REF INT,
    FOREIGN KEY (ID_CATEGORIA_REF) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

-- 5. Pedidos (Para rastrear las compras)
CREATE TABLE PEDIDOS (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO_REF INT,
    FECHA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO_PEDIDO ENUM('PENDIENTE', 'EN_PREPARACION', 'ENTREGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
    TOTAL DECIMAL(10,2),
    FOREIGN KEY (ID_USUARIO_REF) REFERENCES USUARIOS(ID_USUARIO)
);

-- 6. Detalle de Pedidos (La relación muchos a muchos entre pedidos y productos)
CREATE TABLE DETALLE_PEDIDOS (
    ID_DETALLE INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO_REF INT,
    ID_PRODUCTO_REF INT,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_PEDIDO_REF) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO_REF) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

-- 7. Feedbacks (Reseñas de clientes)
CREATE TABLE FEEDBACKS (
    ID_FEEDBACK INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO_REF INT,
    ID_PRODUCTO_REF INT,
    COMENTARIO TEXT,
    CALIFICACION INT CHECK (CALIFICACION BETWEEN 1 AND 5),
    FOREIGN KEY (ID_USUARIO_REF) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_PRODUCTO_REF) REFERENCES PRODUCTOS(ID_PRODUCTO)
);