CREATE DATABASE IF NOT EXISTS ECOMMERCE_BLACK;
USE ECOMMERCE_BLACK;

-- 1. Roles (Admin, Cliente)
CREATE TABLE ROL (
    ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_ROL ENUM ('USUARIO', 'ADMIN') DEFAULT 'USUARIO'
);

-- 2. Usuarios (Combinando tu idea de USUARIOS_ADMIN y Clientes)
CREATE TABLE IF NOT EXISTS USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    IMAGEN_USUARIO VARCHAR(1000),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_ROL_REF INT,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ROL_REF) REFERENCES ROL(ID_ROL)
);

-- 3. Envios (tamble para gestionar los envios a los clientes)
CREATE TABLE IF NOT EXISTS ENVIOS (
ID_ENVIO INT PRIMARY KEY AUTO_INCREMENT,
DIRECCION VARCHAR(1000),
PAIS VARCHAR(300),
CIUDAD VARCHAR(300),
TELEFONO VARCHAR(300),
ID_USUARIOS_REF INT,
FOREIGN KEY (ID_USUARIOS_REF) REFERENCES USUARIOS (ID_USUARIO)
);

-- 4. Categorías (Dama, Caballero, Niños)
CREATE TABLE IF NOT EXISTS CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CATEGORIA VARCHAR(50) NOT NULL,
    IMAGEN_CATEGORIA VARCHAR(1000),
    ESTADO_CATEGORIA ENUM ('DISPONIBLE', 'NO DISPONIBLE') DEFAULT 'DISPONIBLE'
);

-- 5 subcategorias
CREATE TABLE IF NOT EXISTS SUBCATEGORIAS (
ID_SUBCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_SUBCATEGORIA VARCHAR(200),
IMAGEN_SUBCATEGORIA VARCHAR(1000),
ESTADO_SUBCATEGORIA ENUM('DISPONIBLE', 'NO DISPONIBLE') DEFAULT 'DISPONIBLE',
ID_CATEGORIA_REF INT,
FOREIGN KEY (ID_CATEGORIA_REF) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

-- 6. Productos
CREATE TABLE IF NOT EXISTS PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PRODUCTO VARCHAR(250) NOT NULL,
    DESCRIPCION TEXT,
    TALLA VARCHAR(200),
    COLOR VARCHAR(200),
    PRECIO DECIMAL(10,2) NOT NULL,
    STOCK INT DEFAULT 0,
    IMAGEN_PRODUCTO VARCHAR(1000),
    ESTADO ENUM('DISPONIBLE','AGOTADO','NO DISPONIBLE') DEFAULT 'DISPONIBLE',
    ID_SUBCATEGORIA_REF INT,
    FOREIGN KEY (ID_SUBCATEGORIA_REF) REFERENCES SUBCATEGORIAS(ID_SUBCATEGORIA)
);

-- 7. Pedidos (Para rastrear las compras)
CREATE TABLE IF NOT EXISTS PEDIDOS (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO_REF INT,
    FECHA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO_PEDIDO ENUM('PENDIENTE', 'EN_PREPARACION', 'ENTREGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
    TOTAL DECIMAL(10,2),
    FOREIGN KEY (ID_USUARIO_REF) REFERENCES USUARIOS(ID_USUARIO),
    ID_ENVIOS_REF INT,
    FOREIGN KEY (ID_ENVIOS_REF) REFERENCES ENVIOS(ID_ENVIO)
);

-- 8. Detalle de Pedidos (La relación muchos a muchos entre pedidos y productos)
CREATE TABLE IF NOT EXISTS DETALLE_PEDIDOS (
    ID_DETALLE INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO_REF INT,
    ID_PRODUCTO_REF INT,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_PEDIDO_REF) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO_REF) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

-- 9. Feedbacks (Reseñas de clientes)
CREATE TABLE IF NOT EXISTS FEEDBACKS (
    ID_FEEDBACK INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO_REF INT,
    ID_PRODUCTO_REF INT,
    COMENTARIO TEXT,
    CALIFICACION INT CHECK (CALIFICACION BETWEEN 1 AND 5),
    FOREIGN KEY (ID_USUARIO_REF) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_PRODUCTO_REF) REFERENCES PRODUCTOS(ID_PRODUCTO)
);